### ISSUE TITLE
Can't get ls_lidar_driver to work following instructions.

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/ur50_lidar#5]
I had this working before. 

I get now errors when making in catkin, but the instructions would imply you do:

buntu@pi-focal:~/catkin_ws/src$ catkin_make --pkg ls_lidar_driver
Base path: /home/ubuntu/catkin_ws/src
The specified source space "/home/ubuntu/catkin_ws/src/src" does not exist

catkin_make --pkg lslidar_n301_driver does work without errors,

but running the lslidar launch file:

rocess[lslidar_n301_driver_node-2]: started with pid [12191]
ERROR: cannot launch node of type [lslidar_n301_decoder/lslidar_n301_decoder_node]: Cannot locate node of type [lslidar_n301_decoder_node] in package [lslidar_n301_decoder]. Make sure file exists in package path and permission is set to executable (chmod +x)

I think the package as presented here is broken somehow, or the instructions are wrong.  I don't know how I got it to work before the march release./

**Comment by anfederman** [comment]
Still broken.   Does anyone use the LS Lidar any longer?  Surely our customers must be complaining.

**Comment by MoffKalast** [comment]
Good question, I haven't had one to test anything with for weeks. I think there's only one in TP that's tied up with breadcrumb testing.  Thanks for the heads up though, I think the install may be broken on the latest ezmap install scripts since, again, we never tested it.
