### ISSUE TITLE
installing noetic image on PI 3

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/ur50_lidar#9]
Please note that some PI 3 don't have their ethernet named eth0, and you need to substitute the actual interaface name tha starts with 'en.'   In doing this, it may be that the hostname IP is the netplan ethernet as opposed to the wifi, so other ROS things may be broken.

**Comment by MoffKalast** [comment]
Pi 3s are no longer supported.

**Comment by anfederman** [comment]
ARE YOU SERIOUS! Pi 3 not supported for UR50.   Does it work for a UR12?

So if we sell a UR50 to an existing customer who can't get a Pi 4 they are
SOL?

So basically, I can't do any development until I replace a Pi 4.

**Comment by MoffKalast** [comment]
I mean, I'm not aware of any customers that would be in that position. We've only been selling lidars to people roughly 2 years after we abandoned any work or testing on Pi 3s. It could work, but nobody's ever tried to my knowledge. Even the noetic image was never tested nor intended to work on them.

**Comment by anfederman** [comment]
I just need verification that our ur50 code will build and install
following our instructions. I never have done it successfully with our
learn pages. Can someone from scratch install a leshein on a Magni Noetic
with our breadcrumb image and get it to work?

I never have got the catkin_make to work following the lidar.md in
breadcrumb learn.

We should note in docs that it will only work on a PI 4 if that is the case.
